spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:alma
    driver-class-name: org.h2.Driver
    username: alma
    password: AlMa
  jpa:
    hibernate:
      ddl-auto: create
  batch:
    job.enabled: false
    initialize-schema: always
  mail:
    host: mailout.uni-duisburg-essen.de
    port: 587
    defaultEncoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
alma:
  api:
    user:
      key: exampleKey
  source:
    institution:
      id: exampleId
  redirect:
    url: www.uni-due.de/ub
  register:
    email:
      from: information.ub@uni-due.de
logging:
  level:
    org:
      unidue:
        ub:
          unidue:
            almaregister:
              client:
                AlmaUserApiClient: DEBUG