spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    his:
      jdbc-url: jdbc:postgresql://localhost:5432/services
      username: services
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  batch:
    job.enabled: false
    initialize-schema: always
  mail:
    host: mailout.uni-duisburg-essen.de
    port: 587
    defaultEncoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
alma:
  api:
    user:
      key: exampleKey
  source:
    institution:
      id: exampleId
  redirect:
    url: www.uni-due.de/ub
  register:
    email:
      from: information.ub@uni-due.de
logging:
  level:
    org:
      unidue:
        ub:
          unidue:
            almaregister:
              client:
                AlmaUserApiClient: DEBUG